### ISSUE TITLE
Obfs4

### ISSUE THREAD

**Issue by MansurFenix** [Erghel/BridgeMeTheTor#3]
Как установить и находить ли оно obfs4 мосты или только vanilla?

**Comment by SeryiBaran** [comment]
> Как установить

Что установить?

> Находит ли obfs4

Присоединяюсь к вопросу

**Comment by MansurFenix** [comment]
Как что, эту схему как правильно установить чтобы работало 😅

**Comment by SeryiBaran** [comment]
> Как что, эту схему как правильно установить чтобы работало sweat_smile

Так просто копируй мосты в настройки тор/тор браузера

**Comment by MansurFenix** [comment]
> > Как что, эту схему как правильно установить чтобы работало 😅
> 
> Так просто копируй мосты в настройки тор браузера

Я не об этом, как само установка идет, что делать, нету инструкции даже. Получается всегда так когда находишь то что надо

**Comment by MansurFenix** [comment]
У нас не работает к сожалению
